[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/participle"

[[constraint]]
  branch = "master"
  name = "github.com/cnf/structhash"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
